title: "Fashion Forward Techie"
email: arunkumartxx@gmail.com
timezone: UTC
url: "https://fashion-forward.tech/"
baseurl: ""
permalink: "/:title/"
logo: 'assets/images/final-navbar.svg'
favicon: 'assets/images/final-navbar.svg'
author: Sal
paginate: 30
disqus: 'demowebsite'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: UA-113961478-1
show_hero: true
# Authors
authors:
  arun:
    name: Arun Kumar
    display_name: arun
    avatar: 'assets/images/sal.png'
    email: arunkumarbandari309@gmail.com
    web: https://www.wowthemes.net/category/jekyll-themes/
    twitter: https://twitter.com/wowthemesnet
    description: "Author of Affiliates, a template available for WordPress, HTML, Ghost and Jekyll. You are currently previewing Jekyll template demo."
  

# Social
social:
  instagram: https://www.instagram.com/fftechie/
  facebook: https://www.facebook.com/
  twitter: https://twitter.com/

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
